# Generated by Django 2.0.4 on 2018-05-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altcoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deepInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsummary', models.CharField(max_length=2000, unique=True)),
                ('dtotal_supply', models.BigIntegerField()),
                ('dwebsite', models.CharField(max_length=100)),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altcoin.BasicInfo')),
            ],
        ),
    ]
