# Generated by Django 2.0.4 on 2018-05-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altcoin', '0002_deepinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepinfo',
            name='dsummary',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
